# Teste Qui-quadrado
### É uma medida de divergência entre a distribuição dos dados e uma distribuição esperada ou hipotética.
---

In [5]:
import numpy as np
from scipy.stats import chi2_contingency as qui

In [3]:
# Criação da matriz com os dados e execução do teste
novela = np.array([[19,6],[43,32]])
novela

array([[19,  6],
       [43, 32]])

In [6]:
# Segundo valor é o pValue
# Valor de 'p' é maior que 0.05 não há evidencias, portanto, de diferença significativa (hipótese nula):
# Não há diferença significativa.
qui(novela)

(2.037351443123939,
 0.15347667161786666,
 1,
 array([[15.5,  9.5],
        [46.5, 28.5]]))

In [7]:
novela2 = np.array([[22,3],[43,32]])
novela2

array([[22,  3],
       [43, 32]])

In [8]:
# Valor de 'p' é menor que 0.05, podemos regeitar a hipótese nula:
# Há diferença significativa
qui(novela2)

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))